### ISSUE TITLE
Published packages?

### ISSUE THREAD

**Issue by NullVoxPopuli** [alexlafroscia/ember-esbuild#3]
Hi 👋 

I'm staring up experiments on emberclear again, and wanted to try out esbuild. 

Are these packages published?

I'm currently wanting to replace [this mess](https://github.com/NullVoxPopuli/emberclear/blob/master/client/web/emberclear/config/build/workers.js) with esbuild in hopes I can delete 90% of the file.

Thanks! :D

**Comment by alexlafroscia** [comment]
Hey @NullVoxPopuli! This is _really_ rough stuff right now, but I can try to publish some packages as pre-`1.0.0` versions for you to kick the tires on!

I'm currently in the middle of moving to a new house and don't have internet there yet -- I'll get to this in the next few days!

**Comment by NullVoxPopuli** [comment]
All good, these files are pretty small, so I can experiment with copy paste for now :)

Have fun with the move!

**Comment by alexlafroscia** [comment]
Alright, I've published a `1.0.0-beta.0` release of both packages here. I'd love any feedback you have on using them! These are _definitely_ pre-major releases, so expect bugs.

In particular, there is an issue with `ember-cli-babel` that will be resolved with this PR here

https://github.com/babel/ember-cli-babel/pull/368

And `ember-auto-import` is not yet supported by `ember-cli-esbuild` due to it's reliance on `ember-cli-babel`

https://github.com/ef4/ember-auto-import/issues/317
